version: '3'
services:
  app:
    container_name: huhuhu-app
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - 9050:9050
    volumes:
      - .:/project
    stdin_open: true
    tty: true
    command: /bin/sh